name: CI

on:
  push:
    branches:
      - main

  pull_request:
    paths-ignore:
      - '**/*.md'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    name: Check Component
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Check
        run: pnpm check-component

  dispatch_release:
    name: Dispatch Release
    needs: [check]
    if: github.event_name == 'push'
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      ref: ${{ github.ref }}
