name: Release

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

env:
  NPM_CONFIG_PROVENANCE: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to NPM
        uses: changesets/action@v1
        with:
          commit: 'chore(release): [ci] release'
          title: 'chore(release): [ci] release'
          version: pnpm exec changeset version
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
